# -*- coding: utf-8 -*-
"""엄청난 부자2_24-02-19_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ozFpqlvacGiWtvac_mC2NIvhq599f9x7
"""

n, m = map(int, input().split())

print(n//m)
print(n%m)

