# -*- coding: utf-8 -*-
"""이 별은 무슨 색일까_24-02-20_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cyOekX-tRL0P7CeZKCi83qc-DInWcj5O
"""

# 문제
# 스타는 안에 별이 담긴 기계장치를 보았다. 기계장치 내부를 볼 수 없어 별을 구경할 순 없었지만, 기계장치에는 별빛의 파장을 알려주는 계기판이 있었다. 계기판에 표시된 파장의 값을 토대로 스타는 별의 색을 알아낼 수 있었다. 스타가 알아낸 별의 색은 무엇이었을까?

# 색상별 파장의 범위는 다음과 같다.

# 빨간색: 620nm 이상 780nm 이하
# 주황색: 590nm 이상 620nm 미만
# 노란색: 570nm 이상 590nm 미만
# 초록색: 495nm 이상 570nm 미만
# 파란색: 450nm 이상 495nm 미만
# 남색: 425nm 이상 450nm 미만
# 보라색: 380nm 이상 425nm 미만


waveLength = int(input()) # 입력값인 별빛의 파장 값(정수)
waveLength

if 620<=waveLength<=780:
    print('Red')
elif 590<=waveLength<620:
    print('Orange')
elif 570<=waveLength<590:
    print('Yellow')
elif 495<=waveLength<570:
    print('Green')
elif 450<=waveLength<495:
    print('Blue')
elif 425<=waveLength<450:
    print('Indigo')
elif 380<=waveLength<425:
    print('Violet')

